-- Neon/PostgreSQL 16+ foundation. Run on a fresh development database/branch.
-- Additive and transactional: no DROP, TRUNCATE, password reset or data deletion.
BEGIN;
CREATE TABLE IF NOT EXISTS banks (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(32) NOT NULL UNIQUE CHECK(code=upper(code)),
 name VARCHAR(160) NOT NULL,
 currency CHAR(3) NOT NULL DEFAULT 'USD',
 timezone VARCHAR(80) NOT NULL DEFAULT 'UTC',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS branches (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL REFERENCES banks(id),
 name VARCHAR(160) NOT NULL,code VARCHAR(32) NOT NULL,
 UNIQUE(bank_id,id),UNIQUE(bank_id,code)
);
CREATE TABLE IF NOT EXISTS users (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL REFERENCES banks(id),branch_id INTEGER,manager_id INTEGER,
 name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL CHECK(email=lower(email)),password_hash VARCHAR(190) NOT NULL,
 role VARCHAR(32) NOT NULL CHECK(role IN ('marketer','team_leader','branch_manager','regional_manager','head_of_sales','executive','bank_admin')),
 active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(bank_id,id),UNIQUE(bank_id,email),
 FOREIGN KEY(bank_id,branch_id) REFERENCES branches(bank_id,id),
 FOREIGN KEY(bank_id,manager_id) REFERENCES users(bank_id,id),
 CHECK(manager_id IS NULL OR manager_id<>id),CHECK(role<>'branch_manager' OR branch_id IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS users_manager_idx ON users(bank_id,manager_id);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY,bank_id INTEGER NOT NULL,user_id INTEGER NOT NULL,
 csrf_token CHAR(64) NOT NULL,expires_at TIMESTAMPTZ NOT NULL,
 FOREIGN KEY(bank_id,user_id) REFERENCES users(bank_id,id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS leads (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL REFERENCES banks(id),owner_id INTEGER NOT NULL,
 name VARCHAR(160) NOT NULL,company VARCHAR(160) NOT NULL DEFAULT '',email VARCHAR(190) NOT NULL DEFAULT '',
 phone VARCHAR(40) NOT NULL DEFAULT '',source VARCHAR(80) NOT NULL DEFAULT 'Referral',product VARCHAR(120) NOT NULL DEFAULT '',
 status VARCHAR(20) NOT NULL DEFAULT 'new' CHECK(status IN ('new','contacted','qualified','proposal','onboarding','won','lost')),
 notes TEXT NOT NULL DEFAULT '',next_follow_up DATE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(bank_id,id),FOREIGN KEY(bank_id,owner_id) REFERENCES users(bank_id,id)
);
CREATE INDEX IF NOT EXISTS leads_owner_status_idx ON leads(bank_id,owner_id,status);
CREATE TABLE IF NOT EXISTS activities (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL,lead_id INTEGER NOT NULL,user_id INTEGER NOT NULL,
 type VARCHAR(20) NOT NULL CHECK(type IN ('call','visit','meeting','email','task')),
 summary VARCHAR(2000) NOT NULL,due_date DATE,completed BOOLEAN NOT NULL DEFAULT false,
 is_lead_reminder BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 FOREIGN KEY(bank_id,lead_id) REFERENCES leads(bank_id,id),FOREIGN KEY(bank_id,user_id) REFERENCES users(bank_id,id)
);
CREATE INDEX IF NOT EXISTS activities_due_idx ON activities(bank_id,due_date,completed);
CREATE UNIQUE INDEX IF NOT EXISTS activities_lead_reminder_idx ON activities(bank_id,lead_id) WHERE is_lead_reminder;
CREATE TABLE IF NOT EXISTS customers (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL REFERENCES banks(id),owner_id INTEGER NOT NULL,lead_id INTEGER,
 name VARCHAR(160) NOT NULL,company VARCHAR(160) NOT NULL DEFAULT '',email VARCHAR(190) NOT NULL DEFAULT '',phone VARCHAR(40) NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(bank_id,id),UNIQUE(bank_id,lead_id),
 FOREIGN KEY(bank_id,owner_id) REFERENCES users(bank_id,id),FOREIGN KEY(bank_id,lead_id) REFERENCES leads(bank_id,id)
);
CREATE INDEX IF NOT EXISTS customers_owner_idx ON customers(bank_id,owner_id);
CREATE TABLE IF NOT EXISTS opportunities (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL,owner_id INTEGER NOT NULL,customer_id INTEGER NOT NULL,
 title VARCHAR(160) NOT NULL,product VARCHAR(120) NOT NULL DEFAULT '',amount NUMERIC(16,2) NOT NULL DEFAULT 0 CHECK(amount>=0),currency CHAR(3) NOT NULL,
 stage VARCHAR(20) NOT NULL DEFAULT 'new' CHECK(stage IN ('new','qualified','proposal','onboarding','won','lost')),
 expected_close DATE,notes TEXT NOT NULL DEFAULT '',won_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(bank_id,id),FOREIGN KEY(bank_id,owner_id) REFERENCES users(bank_id,id),FOREIGN KEY(bank_id,customer_id) REFERENCES customers(bank_id,id)
);
CREATE INDEX IF NOT EXISTS opportunities_owner_stage_idx ON opportunities(bank_id,owner_id,stage);
CREATE TABLE IF NOT EXISTS targets (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL,user_id INTEGER NOT NULL,
 metric VARCHAR(32) NOT NULL CHECK(metric IN ('leads_created','customers_created','opportunities_won')),
 goal INTEGER NOT NULL CHECK(goal>0),period_start DATE NOT NULL,period_end DATE NOT NULL CHECK(period_end>=period_start),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),FOREIGN KEY(bank_id,user_id) REFERENCES users(bank_id,id),
 UNIQUE(bank_id,user_id,metric,period_start,period_end)
);
CREATE TABLE IF NOT EXISTS products (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bank_id INTEGER NOT NULL REFERENCES banks(id),name VARCHAR(120) NOT NULL,category VARCHAR(80) NOT NULL DEFAULT '',description VARCHAR(2000) NOT NULL DEFAULT '',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(bank_id,id),UNIQUE(bank_id,name)
);
CREATE TABLE IF NOT EXISTS audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,bank_id INTEGER NOT NULL,actor_id INTEGER NOT NULL,
 action VARCHAR(80) NOT NULL,entity VARCHAR(40) NOT NULL,entity_id VARCHAR(40) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 FOREIGN KEY(bank_id,actor_id) REFERENCES users(bank_id,id)
);
CREATE INDEX IF NOT EXISTS audit_bank_time_idx ON audit_events(bank_id,created_at);
-- Persist login throttling across Node/serverless instances; no process-memory-only login protection.
CREATE TABLE IF NOT EXISTS login_throttles (
 key_hash CHAR(64) PRIMARY KEY,attempts INTEGER NOT NULL,window_start TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS schema_migrations (
 version VARCHAR(80) PRIMARY KEY,applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO schema_migrations(version) VALUES ('001-neon-crm') ON CONFLICT DO NOTHING;
COMMIT;
